import bcrypt from "bcryptjs";
// import bed1 from "./assests/bed1.jpg";

const data = {
  users: [
    {
      name: "admin",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: "bed1",
      slug: "brownbed",
      category: "Beds",
      image: "/images/bedAR.jpg", // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: "alpha",
      rating: 4.5,
      numReviews: 10,
      description: "high quality bed",
      arUrl: "https://tasduq.github.io/EcommerceWebXR/start/lecture3_11bed/",
    },
    {
      // _id: '2',
      name: "Bed2",
      slug: "wooden-fit-beds",
      category: "Beds",
      // image: "/images/p2.jpg",
      image: "/images/bed2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Alpha",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '3',
      name: "Bed3",
      slug: "wooden-smart-bed",
      category: "Beds",
      image: "/images/bed3.jpg",
      price: 25,
      countInStock: 15,
      brand: "Alpha",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Chair a",
      slug: "wooden-fit-chairs",
      category: "Chairs",
      image: "/images/chairAR.jpg",
      price: 65,
      countInStock: 5,
      brand: "luma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      arUrl:
        "https://tasduq.github.io/EcommerceWebXR/start/lecture3_11sofachair/",
    },
    {
      // _id: '4',
      name: "Chair b",
      slug: "wooden-small-chairs",
      category: "Chairs",
      image: "/images/chair2.jpg",
      price: 65,
      countInStock: 5,
      brand: "luma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Chair c",
      slug: "wooden-large-chairs",
      category: "Chairs",
      image: "/images/chair3.jpg",
      price: 65,
      countInStock: 5,
      brand: "luma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Sofa a",
      slug: "slim-round-soofa",
      category: "Table",
      // image: "/images/sofa1.jpg",
      image: "/images/tableAR.jpg",
      price: 65,
      countInStock: 5,
      brand: "luma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      arUrl: "https://tasduq.github.io/EcommerceWebXR/start/lecture3_11table/",
    },
    {
      // _id: '4',
      name: "Sofa b",
      slug: "slim-fit-soofa",
      category: "Chairs",
      image: "/images/sofa2.jpg",
      price: 65,
      countInStock: 5,
      brand: "luma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: '4',
      name: "Sofa c",
      slug: "slim-brown-soofa",
      category: "Chairs",
      image: "/images/sofa3.jpg",
      price: 65,
      countInStock: 5,
      brand: "luma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
